### ISSUE TITLE
Error undefined is not a function at Track.createDirs 

### ISSUE THREAD

**Issue by ferserg** [Lordmau5/node-spotify-downloader#32]
Trying to download this playlist https://play.spotify.com/album/2KPL3UpVUBQxgVOCX91xEE, it shows this error

Login successful!
Handling album ...
Album: So No Forevis
Processing 14 tracks
Error on track: "Raimundos - Só No Forevis - Selim [Participação Especial de Marcelo D2]" : TypeError: undefined is not a function 

TypeError: undefined is not a function
    at Track.createDirs (/Users/ferserg/Downloads/node-spotify-downloader-master/server/lib/track.js:112:18)
    at Track.createDirs (/Users/ferserg/Downloads/node-spotify-downloader-master/server/lib/track.js:4:59)
    at /Users/ferserg/Downloads/node-spotify-downloader-master/server/lib/track.js:61:26
    at /Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/lib/spotify.js:865:5
    at Spotify.<anonymous> (/Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/lib/spotify.js:773:5)
    at fn (/Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/lib/spotify.js:490:10)
    at Spotify._onmessage (/Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/lib/spotify.js:506:5)
    at WebSocket.emit (events.js:110:17)
    at Receiver.ontext (/Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:798:10)
    at /Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:473:18
    at Receiver.applyExtensions (/Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:360:5)
    at /Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:462:14
    at Receiver.flush (/Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:336:3)
    at Receiver.opcodes.1.finish (/Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:478:12)
    at Receiver.expectHandler (/Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:453:31)
    at Receiver.add (/Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:91:24)
    at TLSSocket.firstHandler (/Users/ferserg/Downloads/node-spotify-downloader-master/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:775:22)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by serjum** [comment]
do you use windows os ?

**Comment by ferserg** [comment]
My OS is OS X El Capitan

**Comment by rafaeldamasceno** [comment]
@serjum https://github.com/rafaeldamasceno/node-spotify-downloader/blob/master/server/server.coffee#L40 should read `node` instead of `nodejs` too.

**Comment by serjum** [comment]
@ferserg , should be fixed, can you confirm? If it isn't can you provide more details about how you run script?

**Comment by ferserg** [comment]
Problem solved, thanks to all !

**Comment by ferserg** [comment]
Problem solved, thanks to all !
