### ISSUE TITLE
Has no method endsWith

### ISSUE THREAD

**Issue by lenisko** [Lordmau5/node-spotify-downloader#33]
When trying to download
```
Error on track: "Toby Green - Everytime" : TypeError: Object Toby Green - Everytime has no method 'endsWith' 

TypeError: Object Toby Green - Everytime has no method 'endsWith'
    at Track.createDirs (/home/spot/node-spotify-downloader/lib/track.js:112:18)
    at Track.createDirs (/home/spot/node-spotify-downloader/lib/track.js:4:59)
    at /home/spot/node-spotify-downloader/lib/track.js:61:26
    at /home/spot/node-spotify-downloader/node_modules/spotify-web/lib/spotify.js:865:5
    at Spotify.<anonymous> (/home/spot/node-spotify-downloader/node_modules/spotify-web/lib/spotify.js:773:5)
    at fn (/home/spot/node-spotify-downloader/node_modules/spotify-web/lib/spotify.js:490:10)
    at Spotify._onmessage (/home/spot/node-spotify-downloader/node_modules/spotify-web/lib/spotify.js:506:5)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.ontext (/home/spot/node-spotify-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:798:10)
    at /home/spot/node-spotify-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:473:18
    at Receiver.applyExtensions (/home/spot/node-spotify-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:360:5)
    at /home/spot/node-spotify-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:462:14
    at Receiver.flush (/home/spot/node-spotify-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:336:3)
    at Receiver.opcodes.1.finish (/home/spot/node-spotify-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:478:12)
    at Receiver.expectHandler (/home/spot/node-spotify-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:453:31)
    at Receiver.add (/home/spot/node-spotify-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:91:24)
    at CleartextStream.firstHandler (/home/spot/node-spotify-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:775:22)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:746:14)
    at CleartextStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at _stream_readable.js:401:7
    at process._tickDomainCallback (node.js:459:13)
```

**Comment by lenisko** [comment]
Nvm... was still on 0.1* node version
