### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ethus3h** [Lordmau5/node-spotify-downloader#42]
Two different errors:
```
   - Done: [...]
   - Error received: Error: ENOENT: no such file or directory, unlink '/[...].mp3.jpg'
 - Downloading: 
```
```
   - Done: [...]
   - Error received: TypeError: Cannot read property 'send' of null
   - Error received: TypeError: Cannot read property 'send' of null
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'send' of null
    at Spotify.sendCommand (/Users/elliot/node-spotify-downloader/node_modules/spotify-web/lib/spotify.js:640:12)
    at Spotify.sendProtobufRequest (/Users/elliot/node-spotify-downloader/node_modules/spotify-web/lib/spotify.js:749:8)
    at Spotify.get.Spotify.metadata (/Users/elliot/node-spotify-downloader/node_modules/spotify-web/lib/spotify.js:853:8)
    at Track.process (/Users/elliot/node-spotify-downloader/lib/track.js:52:27)
    at Track.process (/Users/elliot/node-spotify-downloader/lib/track.js:4:59)
    at Downloader.processTrack (/Users/elliot/node-spotify-downloader/lib/downloader.js:163:25)
    at /Users/elliot/node-spotify-downloader/lib/downloader.js:4:59
    at /Users/elliot/node-spotify-downloader/node_modules/async/lib/async.js:246:17
    at iterate (/Users/elliot/node-spotify-downloader/node_modules/async/lib/async.js:146:13)
    at /Users/elliot/node-spotify-downloader/node_modules/async/lib/async.js:157:25
    at Track.<anonymous> (/Users/elliot/node-spotify-downloader/node_modules/async/lib/async.js:248:21)
    at Domain.<anonymous> (/Users/elliot/node-spotify-downloader/lib/track.js:184:65)
    at emitOne (events.js:90:13)
    at Domain.emit (events.js:182:7)
    at emitError (domain.js:66:24)
    at Domain.errorHandler [as _errorHandler] (domain.js:110:18)
    at process._fatalException (node.js:255:33)
    at Domain.errorHandler [as _errorHandler] (domain.js:137:26)
    at process._fatalException (node.js:255:33)
```

**Comment by ethus3h** [comment]
A few more possibly related issues I posted in the Gitter:

Having some weird issues with the number of tracks in playlists being a few fewer than Spotify once imported into iTunes. Not sure what that's about. I wondered if it was iTunes merging duplicate tracks on import, but it should still include two instances of the merged track when importing by dragging directly into a playlist (it doesn't in this case), so I don't think it's that. Also, it would be good to document in the README how to resume after the download has been interrupted — it seems to leave truncated files. Also, ID3 tags seem to be arbitrarily missing from some files, but IDK why. And it just stopped after a "Cover downloaded:" message, with no error, just taking me back to the command prompt
