### ISSUE TITLE
TrackError: Account subscription status not Spotify Premium

### ISSUE THREAD

**Issue by HomeroMx** [Lordmau5/node-spotify-downloader#53]
Hello everyone, today I get this error:

```
Login successful!
Handling playlist ...
Playlist: Sólo Pop
Processing 50 tracks
 - Downloading: Thalía - Vuélveme a Querer
   - Cover downloaded: Thalía - Vuélveme a Querer
   - Error received: TrackError: Account subscription status not Spotify Premium
```
This error is repeated in all the songs.

Does this happen to anyone else?

Thanks....

HMx

**Comment by uniZero** [comment]
Can also confirm this. I am also experiencing the same error.

```
Login successful!
Handling playlist ...
Playlist: Listen Up
Processing 61 tracks
 - Downloading: Vic Mensa - Dynasty
   - Cover downloaded: Vic Mensa - Dynasty
   - Error received: TrackError: Account subscription status not Spotify Premium
```

**Comment by kelvinss** [comment]
Yeap, this error is started happening even with Premium accounts. We don't know why.

**Comment by kelvinss** [comment]
Yeap, this error is started happening even with Premium accounts. We don't know why.

**Comment by rafaeldamasceno** [comment]
Hey, it looks like this was just the Spotify API acting up. It's all working fine here, now.

**Comment by swablueme** [comment]
I'm getting the same error now. ;;

**Comment by angeloruggieridj** [comment]
It doesn't work with free account... Any idea?

**Comment by kelvinss** [comment]
The error persistis using my premium account. The guys on node-spotify-web are talking about this: https://github.com/TooTallNate/node-spotify-web/issues/111#issuecomment-224489010

**Comment by vmirage** [comment]
Seems like an intermittent error. I made a patch to workaround the issue by reattempting log in until it is able to successfully play a track.

https://github.com/vmirage/node-spotify-downloader/commit/346ff12620a1b03b998ad2ad216641a797c46ab5

**Comment by angeloruggieridj** [comment]
It works again this morning

**Comment by angeloruggieridj** [comment]
It starts working but it stops after 2 albums that I've downloaded...

**Comment by angeloruggieridj** [comment]
OK i've discovered this:
- Open the run.bat
- Download
- If it doesn't download anything (and show the error of Premium Account), close Node.JS app and CMD
- Then restart again and re-open the browser page

**Comment by angeloruggieridj** [comment]
With the patch of vmirage works very well!
Thanks man

**Comment by Dexterlab1** [comment]
any way to do a little visual executable file (exe), for those who are not very technical matters in these commands.

**Comment by HomeroMx** [comment]
`Login successful!
Checking for Spotify Premium subscription error...`

since this morning my end says that, does nothing more ... any ideas?


Thanks a lot....

**Comment by morganjacklee** [comment]
@HomeroMx I had the same thing. Fixed it by choosing to save in a single folder, unsure why...

**Comment by HomeroMx** [comment]
Thanks @morganjacklee this log is with "download to single folder" active:

`Login successful!
Checking for Spotify Premium subscription error...
Spotify Premium subscription check finished.
Handling playlist ...
Playlist: Sólo Pop

C:\nspdown\node_modules\spotify-web\lib\spotify.js:773
    fn(null, data);
    ^
TypeError: makeB64 is not a function
    at C:\nspdown\lib\downloader.js:127:33
    at Spotify.<anonymous> (C:\nspdown\node_modules\spotify-web\lib\spotify.js:773:5)
    at fn (C:\nspdown\node_modules\spotify-web\lib\spotify.js:490:10)
    at Spotify._onmessage (C:\nspdown\node_modules\spotify-web\lib\spotify.js:506:5)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (C:\nspdown\node_modules\spotify-web\node_modules\ws\lib\WebSocket.js:798:10)
    at C:\nspdown\node_modules\spotify-web\node_modules\ws\lib\Receiver.js:473:18
    at Receiver.applyExtensions (C:\nspdown\node_modules\spotify-web\node_modules\ws\lib\Receiver.js:360:5)
    at C:\nspdown\node_modules\spotify-web\node_modules\ws\lib\Receiver.js:462:14
    at Receiver.flush (C:\nspdown\node_modules\spotify-web\node_modules\ws\lib\Receiver.js:336:3)
    at Receiver.opcodes.1.finish (C:\nspdown\node_modules\spotify-web\node_modules\ws\lib\Receiver.js:478:12)
    at Receiver.expectHandler (C:\nspdown\node_modules\spotify-web\node_modules\ws\lib\Receiver.js:453:31)
    at Receiver.add (C:\nspdown\node_modules\spotify-web\node_modules\ws\lib\Receiver.js:91:24)
    at TLSSocket.firstHandler (C:\nspdown\node_modules\spotify-web\node_modules\ws\lib\WebSocket.js:775:22)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:531:20)`

**Comment by jonaaa20** [comment]
Thanks for the patch @vmirage, working fine now ;)

**Comment by aroundthecorner** [comment]
It was working for a few hours after @vmirage patch. Now i got another error

Login successful!
Checking for Spotify Premium subscription error...
Spotify Premium subscription check finished.
Handling track ...
Processing 1 tracks
 - Downloading: Mega - Bayangan Gurauan
   - Cover downloaded: Mega - Bayangan Gurauan
   - Error received: Error: EPERM: operation not permitted, open 'C:\node-spotify-downloader-master\download\Mega - Bayangan Gurauan.mp3'
 ------- DONE ALL -------

**Comment by kelvinss** [comment]
@aroudthecorner That seems not related to Spotify API

**Comment by Crosant** [comment]
Having the same problem as @HomeroMx nothing happens after 
"Checking for Spotify Premium subscription error..."

**Comment by thebdl** [comment]
Having the same problem as @HomeroMx nothing happens after 
"Checking for Spotify Premium subscription error..."

**Comment by HomeroMx** [comment]
I tried the "download to single folder" option, but it does not work.

Greetings...

**Comment by jonaaa20** [comment]
Okay, let me explain, the problem is:

Wrong urls or maybe spotify is trying to "block" the tool, we don't know what's the main problem yet...
